---

- name: installing packages
  hosts: prod
  become: yes
  gather_facts: no
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: latest

    - name: starting-httpd
      service:
        name: httpd
        state: started

