---
- name: Loop concept
  hosts: prod
  become: yes
  tasks:
   - name: installing httpd
     yum:
        name: "{{item}}"
        state: latest
     loop:
      - httpd
      - git
      - docker

   - name: starting-httpd
     service:
       name: httpd
       state: started