---
- name: installing git package
  hosts: prod
  become: yes
  tasks:
    - name: install EPEL repo
      yum: 
       name: epel-release 
       state: present
    - name: installing nginx
      yum:
        name: nginx
        state: present

    - name: starting service
      service:
        name: nginx
        state: started