- name: prod-variables-play1
  hosts: prod
  become: yes
  
  tasks:
   - name: printing name using variables
     vars:
      - my_name: pavan
      - my_age: 24
     debug: 
        msg: "my name is {{my_name}} and {{my_age}}"
   - name: printing name using variables
     
     debug: 
        msg: "my name is {{my_name}} and {{my_age}}"

- name: all-host-variables-play2
  hosts: all
  become: yes
  tasks:
   - name: printing name using variables
     debug: 
        msg: "my name is {{my_name}} and {{my_age}}"

- name: variables-play3-with global variables
  hosts: all
  become: yes
  vars:
    - my_name: kumar
    - my_age: 24
  tasks:
   - name: printing name using variables
     debug: 
        msg: "my name is {{my_name}} and {{my_age}}"